### ISSUE TITLE
Discard report not sorted by StockNumber

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#10]
The Discard Report for storage doesn't sort the items:
![capture](https://user-images.githubusercontent.com/38472884/38888176-d88c2a06-4248-11e8-9221-bfdb23107e24.PNG)
These appear mostly sorted but not all of the 03 and 04 boxes are grouped together.

**Comment by kidclamp** [comment]
This should be fixed
