### ISSUE TITLE
Discard Report not indicating type of item

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#11]
I do not know how Location is being worked out, but previously the Location indicated the Warehouse and an "item type" with a Location code, for example wfilm is a film in Warehouse.

The Discard report (pull sheet) should indicate something like that.
![image](https://user-images.githubusercontent.com/38472884/38888383-7597c60c-4249-11e8-8271-388a09b441e2.png)
For example this first row is a wfilm. Maybe another column can be added?

**Comment by kidclamp** [comment]
That row is now included - would you prefer to see the codes (as they show now) or the descriptions?

e.g.
wrhse OR "Library Service Center Prosperity Road"
same question for item types
SPEC OR "In House"

**Comment by todds1vtedu** [comment]
The Location on Sierra has values wfilm, wvideo, wfiche, which is what I was talking about.
I need to talk with Jessica to see what they have done with Location and plan to handle this info.
I need to get back to you.

**Comment by kidclamp** [comment]
Ah, okay, I renamed the current location to 'Holding branch' and added 'Location' which is the wfilm - I read it and assumed item type, sorry about that

Try it now

**Comment by todds1vtedu** [comment]
looks good! 
idk if I am supposed to close th eissue...

**Comment by kidclamp** [comment]
I can, you can too in the future :-) (once you are happy that is)
