### ISSUE TITLE
Discard Report 'range'

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#12]
We don't create a Discard List from a range of call numbers. We never have a sequential range of numbers.
We create a Discard List from a list of call numbers, e.g.
pq1.a8
pq2.e83
pq2177.a2 a5
pq6001.h55
pq6001.j68

The way we do it now, we can see how many total we have every time we add another call number, and we stop when we get about 200 items to pull. But that part isn't really required, and doing them 1 at a time would be OK, but not great.

**Comment by kidclamp** [comment]
This is now updated, please test and give feedback

**Comment by todds1vtedu** [comment]
I have comments on the "Pull Discarded" Issue. I am closing this because it is kind of a dup.
