### ISSUE TITLE
Discard Report additional column and rearrange columns

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#13]
I just talked to Jessica to understand terminology/field names and what info is in which field.
Is the "Holding Branch" column actually the Shelving Location? If so, I would call it that. And add the Home Library as a new column beside it. 

And could you arrange the columns beginning with StockNumber, barcode, call number, volume, Shelving Location, Title. We do not really need Author, Home Branch, Item Type for this report.

**Comment by kidclamp** [comment]
Holding branch is the branch the item is currently at 

For instance - if a book with a Home Branch of Library Service Center Energy Drive (rstore) is checked in at Newman - the 'holdingbranch' would be 'newman' while the 'homebranch' would remain 'rstore'

The shelving locations in the system seem to combine homebranch/location so I think that is where our vocabularies are confused.

Basically all of the koha columns are listed here, with brief explanations:
http://schema.koha-community.org/master/tables/items.html

It sounds like you only need location and neither homebranch or holdingbranch for this report

**Comment by todds1vtedu** [comment]
We could use all 3 (shelving, holding, and home), but I think that is too much.
We want Shelving location and Holding Branch

**Comment by kidclamp** [comment]
Updated, please test

**Comment by todds1vtedu** [comment]
It looked fine before the new load, which made Pull Discards completely break, nothing returned/displayed. I made this comment on another open issue, so I am closing this one.
