### ISSUE TITLE
Rearranging the columns on the Pull Sheet report

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#14]
I will just list the order we would like. You can get rid of the Author column.
Here is the order we would like: StockNumber, barcode, call num, volume, Shelving Location, Requester, Destination, Hold Notes.

Let me know if there are problems! thanks

**Comment by kidclamp** [comment]
Do you still want 'Title' and where would that go?

**Comment by todds1vtedu** [comment]
Between Volume and Shelving Location. Could you just display the first 20 char of the title? It is funny that Sierra couldn't retrieve titles efficiently enough to display them, so no one even looks at them here. Most of us look for a volume if there is one, and then the barcode. Even call numbers aren't used much at storage because they are at the bottom of the spine at the bottom of a box (and too hard to see).

**Comment by kidclamp** [comment]
Updated, please test
