### ISSUE TITLE
preciseness of spacing on call numbers

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#16]
For the Pull Discard Items, do we have to have the exact spacing and . (dots) in the call number for it to match. It seems like the case of letters doesn't matter, but pq1.a8 does not match, whereaws pq1 .a8 does. I have gotten used to leaving out spaces and dots, e.g. pq1a8.  Luckily, I am entering call numbers from a lis given to me so I know where spaces and dots are.

Are we matching on exactly how a call number is entered in the system or you always need a space before a dot? or what are the matching rules, please?

**Comment by kidclamp** [comment]
You are correct, the match is case insensitive, however, spaces and dots do currently matter. It is doing a mysql comparison which is why it is case insensitive

**Comment by todds1vtedu** [comment]
We had a little discussion about this in the morning meeting. While this might be OK for the staff interface, it seems like a problem for patrons if it is the same in their interface. And if that is going to be fixed to more forgiving on entering call numbers, maybe the staff interface can also be made more forgiving.

**Comment by kidclamp** [comment]
Hi Todd,

I think you are referring to things outside of the storage plugin here, am I correct?

-Nick

**Comment by todds1vtedu** [comment]
yes, this is for any search or place you are specifying a call number.

**Comment by kidclamp** [comment]
Hi Todd,

You should take this one to the implementation group to file a ticket, it is outside the scope of this plugin.

-Nick
