### ISSUE TITLE
InventoryNumber and StockNumber

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#17]
I see Stock Number used as the header label for remote storage's location id, and I see InventoryNumber on Search results, but they seem to contain the same values.

We need to be able to Search on these values so, I was **ecstatic** (Hi Joy) when I saw our location ids displayed there and that we could search on Inventory Number! Are they the same field (I hope)? Can we label then the same, please?

**Comment by kidclamp** [comment]
Hi Todd,

I dolbelieve these are the same fields with different labels

Can you specify where you see the different labels so I can try to make them the same?

-Nick

**Comment by talljoy** [comment]
Hi Todd!!

**Comment by todds1vtedu** [comment]
One o the Item Search options in the Barcode drop-down is Inventory Number. Inventory Number is also a column displayed. We need this!  I would make these both (in order of my personal preference because no one else seems to care particularly) LSC Location or LSC Shelf or LSC Loc or LSC ID or LSC Number. LSC is Library Service Center, btw.

**Comment by kidclamp** [comment]
Hi Todd,

I am still unsure of which page you are talking about, can you take some screenshots?

-Nick

**Comment by todds1vtedu** [comment]
All of these also have a column to StockNumber column header (our remote shelf number) and the main Item Search can use Inventory Number to search. Inventory Number **is** our Stock Number. #17 

![image](https://user-images.githubusercontent.com/38472884/40080816-2a89c242-585a-11e8-9ef5-5b68d0154bcf.png)

I put this in a related Issue too. #22

**Comment by kidclamp** [comment]
HI Todd,

For the item search we would need to ad to the system preference IntranetUserJS, so this is outside the storage plugin scope. The code below should do what you want

$("option[value='stocknumber']").text("LSC Location");

Can you take that to the implementation group and have them open a ticket listing anywhere else they would like this changed? Or someone with access can add that code in to the preference and voila.

-Nick
