### ISSUE TITLE
alt-key or shortcut or spacebar

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#19]
In Sierra, pop-up boxes or default actions/buttons are executed when you hit the space bar.
This allows quick removal of constant pop-ups.
Other systems use hot keys or alt-keys.
We are going to have a lot of pop-ups with 3 buttons for ConfirmHold&Transfer and CoonfirmHold&Transfer&Print and Ignore. Can we make ConfirmHold&Transfer be activated with a simple keystroke (like a space)?

**Comment by kidclamp** [comment]
This one may be possible, but I think it would affect more than just the storage plugin, I am going to bring this one up at our next meeting here and see what we think is best.

**Comment by todds1vtedu** [comment]
Check Out seems to have something like this:
![image](https://user-images.githubusercontent.com/38472884/39446885-f21cb266-4c8d-11e8-8a9f-c0dbd8deffcd.png)
Am I correct?

**Comment by kidclamp** [comment]
Looking into this it could be done for the holds confirmation boxes, it would be a small development estimated at $1000, let us know if you want to pursue it

**Comment by todds1vtedu** [comment]
I will convey the option! thanks

**Comment by kidclamp** [comment]
Hi Todd,

Would you like to keep this issue open? Or can we close this now and open a ticket if you choose to move ahead?

-Nick

**Comment by todds1vtedu** [comment]
I do not mind if you close it. Someone can make a ticket if they want to deal with this in general.
