### ISSUE TITLE
Problems with Scan info on holdshelf/transit slips

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#21]
SOMETIMES, when we have a scan request item and select Confirm and Print, th eINfo on the pop-up contains the correct information for the scan request, but the info on the Print screen and the printout are for a different scan request. e.g. these items:1000772058 and 1000772058
Many other scan request are printing perfectly fine!

**Comment by kidclamp** [comment]
Hi Todd,
I think this is in the checkin screen when confirming a hold? If so I want to open a support ticket as it is a Koha issue, not a plugin issue.

-Nick

**Comment by todds1vtedu** [comment]
Yes kind of. The information on the checkin popup is fine, but it **prints** the wrong info. So, I am guessing it has to do with the code you wrote for us to print that, but I cannot tell. It *seems* like it is wrong when there are multiple different **volumes** in the same **Journal** having scans. The popup contains the correct article, page numbers, etc. for the scan, but the printout of it contain the _first_ volume's scan info.

-Todd

**Comment by kidclamp** [comment]
Hi Todd,

Joy is going to open a ticket for this one, I think the problem is outside fo the storage plugin code

-Nick

**Comment by todds1vtedu** [comment]
yes
