### ISSUE TITLE
Reshelve report

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#22]
I think I had this in another ticket and it got lost. For the reshelve report, we would like the Barcode colume move to be the second column. Can you re-bane the Enumchron column to Volume. Also, you limited the Title to the first 20 char in other reports, can you do it on this report too.

All of the reports (View Transfers, Reshelve, Create Pull List, Inventory, Discards, and Move) have column Headers called Enumchron, which should be changed to **Volume**.

All of these also have a column to StockNumber column header (our remote shelf number) and the main Item Search can use Inventory Number to search. Inventory Number **is** our Stock Number. #17 

![image](https://user-images.githubusercontent.com/38472884/40080816-2a89c242-585a-11e8-9ef5-5b68d0154bcf.png)

**Comment by kidclamp** [comment]
Column names updated within plugin, order changed, the lastest version is installed, let me know if there are any problems
