### ISSUE TITLE
Move Items display/functionality

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#23]
Can we have the  number of items to display  default to 'all'?
![image](https://user-images.githubusercontent.com/38472884/40139561-42ff2cd0-591e-11e8-897c-a2553681eaa8.png)

'Select All' should should select all, not select all of them on the display.
We have problems not moving all items to a new box because only 20 display by default, and when we select all to move, only the first 20 move.

**Comment by kidclamp** [comment]
All items will now show on page load
