### ISSUE TITLE
Reshelve Report

### ISSUE THREAD

**Issue by talljoy** [bywatersolutions/koha-plugin-storage#3]
For the reshelving report, can this be ordered in 'stocknumber order'.  And by that they mean mainly the first and last grouping in the stocknumber field.

Stocknumber = A1L0101 0003627 09
Would like to order by A1L0101 09  (ignore the center bit)
There may be a slightly different pattern to the warehouse items (starts with P)

If not possible, or too difficult, then just a 'normal' sort is desired.

**Comment by kidclamp** [comment]
This should be working
