### ISSUE TITLE
Reshelve Report

### ISSUE THREAD

**Issue by talljoy** [bywatersolutions/koha-plugin-storage#4]
Change columns - 
REMOVE: public note and internal note
Have these columns:
stocknumber, call #, enumchron, title, author, barcode, status, transit status

Status - lost, damaged, withdrawn
transit status - is this possible?  The idea here is to spot errors on items that weren't checked in at storage or should be going somewhere else to fill a hold.

**Comment by kidclamp** [comment]
added
