### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by talljoy** [bywatersolutions/koha-plugin-storage#6]
They would like:
1. Show us what *should* be in the box  (all the contents)
2. Show us what we scanned that is in the correct box (in green)
3. Show us what we scanned that is misfiled - should be in a different box (in red)

**Comment by talljoy** [comment]
Also, can you add status and transit status to the report?

**Comment by kidclamp** [comment]
Unscanned items at bottom of table (in purple)
Statuses added
